### ISSUE TITLE
NameError: name 'filepath' is not defined

### ISSUE THREAD

**Issue by tenandten** [chigozienri/VQGAN-CLIP-animations#17]
Hi 
I'm getting this error after upscaling frames and trying to "make a video of the results".  I wasn't having any issues initially, but have since had a hard time upscaling, creating, and doing the slow mo.  
Restarting runtime and going through a few cells sometimes helps.  Changing the 'i' to the last frame seems to work intermittently.
If you could help me understand if I'm doing something wrong, I'd really appreciate it. I am a total noob, so i feel like a caveman trying to troubleshoot this. 
Thank you
<img width="750" alt="Screen Shot 2021-09-20 at 11 24 07 AM" src="https://user-images.githubusercontent.com/91088024/134054418-8fb1b65f-5c49-4911-9294-d44e01503b34.png">
<img width="984" alt="Screen Shot 2021-09-20 at 9 34 19 AM" src="https://user-images.githubusercontent.com/91088024/134054496-6f26674d-3d87-4e6e-b01e-fd8c4c42b41f.png">
!!

**Comment by tenandten** [comment]
So I think I may have solved my problem.  When I was setting 711x400 pixels I was getting errors.  Now I'm using 533x300 and not getting any of the same issues.  I guess that's all it was.

**Comment by chigozienri** [comment]
Oh, great! I'll see if I can work out what the maximum resolution colab can normally handle is (it's a bit tricky because google gives different machines at different times), and put in a warning if people go above that. I won't close this issue just yet, until I have better warnings in place. Let me know if you have any more problems.

**Comment by tenandten** [comment]
Everything is working beautifully now, thanks again! Just needed to trouble shoot that and also that I need to delete the slow-mo files from vqgan folder before making another.
Would it be possible to add a feature where it downloads the steps images before deleting them?
Thanks again, loving it!

**Comment by chigozienri** [comment]
> Would it be possible to add a feature where it downloads the steps images before deleting them?

How do you mean? The steps are already available in google drive, if you use it, or you can download them manually through the file browser if not. I think I would prefer to let the users deal with the images as they wish, rather than forcing them to delete or download them, but if you have a particular workflow in mind I could consider it. Closing this issue now, but feel free to open a feature request issue if you can describe your vision in more detail. Thanks!
