### ISSUE TITLE
Import Error:  ---> 26 from taming.models import cond_transformer, vqgan

### ISSUE THREAD

**Issue by tim-andes** [chigozienri/VQGAN-CLIP-animations#24]
**Describe the bug**
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-dbaa526c00d0> in <module>()
     24 from omegaconf import OmegaConf
     25 from PIL import Image
---> 26 from taming.models import cond_transformer, vqgan
     27 import torch
     28 from torch import nn, optim

3 frames
/content/taming-transformers/taming/data/helper_types.py in <module>()
----> 1 from typing import Dict, Tuple, Literal, Optional, NamedTuple, Union
      2 
      3 from PIL.Image import Image as pil_image
      4 from torch import Tensor
      5 

ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

**Parameters used**
Did not get to parameters

**Which cell you saw the error in**
"# @title Loading of libraries and definitions"

**Error message**
See above

**Comment by AparnaLiza** [comment]
Hi, so it is getting quite difficult to find the solution for the error. 

`ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-12-c026441db553>](https://localhost:8080/#) in <cell line: 13>()
     11 from omegaconf import OmegaConf
     12 from PIL import Image
---> 13 from taming.models import cond_transformer, vqgan
     14 import torch
     15 from torch import nn, optim

2 frames
[/content/./taming-transformers/taming/data/utils.py](https://localhost:8080/#) in <module>
      9 import torch
     10 from taming.data.helper_types import Annotation
---> 11 from torch._six import string_classes
     12 from torch.utils.data._utils.collate import np_str_obj_array_pattern, default_collate_err_msg_format
     13 from tqdm import tqdm

ModuleNotFoundError: No module named 'torch._six'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.`

**Comment by AparnaLiza** [comment]
Hi, so it is getting quite difficult to find the solution for the error.

#38 

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-12-c026441db553>](https://localhost:8080/#) in <cell line: 13>()
     11 from omegaconf import OmegaConf
     12 from PIL import Image
---> 13 from taming.models import cond_transformer, vqgan
     14 import torch
     15 from torch import nn, optim

2 frames
[/content/./taming-transformers/taming/data/utils.py](https://localhost:8080/#) in <module>
      9 import torch
     10 from taming.data.helper_types import Annotation
---> 11 from torch._six import string_classes
     12 from torch.utils.data._utils.collate import np_str_obj_array_pattern, default_collate_err_msg_format
     13 from tqdm import tqdm

ModuleNotFoundError: No module named 'torch._six'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```
