### ISSUE TITLE
Optional: SRCNN for increasing resolution –  upscaled images don't get saved when using GPU runtime

### ISSUE THREAD

**Issue by metabeanz** [chigozienri/VQGAN-CLIP-animations#7]
https://colab.research.google.com/github/chigozienri/VQGAN-CLIP-animations/blob/main/VQGAN-CLIP-animations.ipynb

They get saved ok when using TPU runtime (but this is too slow). They seem to go missing when using  GPU runtime.

Might well be a fault I'm making as I am a fumbling luddite, but the above seems true when no other parameters are changed so I don't know why it would be.

works amazingly otherwise

**Comment by chigozienri** [comment]
The whole notebook is not designed to use with the TPU runtime, so I'm not surprised it's slow.

If you switch runtimes partway through the run, any saved files and any variables in memory will disappear, and if you haven't been using the google drive connection you won't be able to get them back. You should be using the GPU runtime from the beginning, and not switch it.

I can't replicate the issue from your description. The files should be saved in the steps directory (the location of this will depend on if you are using google drive or not) and are named zoomed_[FRAMENUMBER].png. Perhaps search your google drive for "zoomed"?

Otherwise, if you can give a more detailed description so that I can replicate it, I might be able to help.

**Comment by metabeanz** [comment]
It's strange - I haven't switched runtimes part way through. I'm using google drive and there are no results for zoomed, other than the ones that were from TPU runtimes.

When I use TPU the zoomed files are in the steps folder along with the smaller files. When I use GPU only the smaller files are there, even though the runtime shows it has completed the upscaling. They are simply not to be found.

I haven't modified anything other than the standard promt/width/height/zoom etc parameters. I'm stumped

**Comment by metabeanz** [comment]
I just ran a screen recording to try and show you what I meant and now the zoomed files are showing up lolll.
It appears I am actually a stump. Sorry about that.
It was strange how they showing up before. I'm so happy it's working now anyway and thank you for making this amazing mod!

**Comment by chigozienri** [comment]
No problem! Glad it's working.
